### PR TITLE
perf: implement static vector allocation & error handling

### PR DESCRIPTION
**Pull request by vschwaberow**
- [X] I already read and understand the [contribution guide](https://github.com/latipun7/.github/blob/main/contributing.md#pull-requests "Pull Request Guide")

---

* Optimized bubble types and put them to const
* Implemented proper error handling -> avoid unwrap_or_else because of panic (Avoid unwrap)
* Implemented a static allocation for Vector which avoids permanent alloc while pushing

### CODE REVIEW

**Review by latipun7 — APPROVED** [review]
As always, you are the MVP 😁 Thank you very much ✨🚀

**Comment by vschwaberow** [comment]
Somehow my linter fails. Any suggestions?

**Comment by latipun7** [comment]
just install latest rust with [rustup](https://www.rust-lang.org/tools/install) (default would install clippy and rustfmt too). Then before commit, just run `cargo clippy` & `cargo fmt --all` on project root directory 👌

**Comment by vschwaberow** [comment]
Thanks. Next time clippy will take care of formatting.

**Comment by vschwaberow** [comment]
Thank you for this pleasant and relaxed work environment. We are constantly learning from each other.

**Pull request merged**
